name: 其他
description: 其他问题反馈
title: '[其他]：'
labels: ['other']
body:
  - type: textarea
    id: detail
    attributes:
      label: 详细信息
      description: 详细描述问题
    validations:
      required: true
