name: 模组翻译反馈
description: 模组翻译的质量、建议反馈
title: '[模组翻译]：'
labels: ['translation feedback']
body:
  - type: input
    id: modpack_info
    attributes:
      label: 简体中文资源包信息
      description: 当前所使用资源包的打包时间
      placeholder: 如 2021-11-08 14:24
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 详细信息
      description: 详细描述翻译相关问题
      value: |
        - 模组英文名称：
        - 模组版本：
    validations:
      required: true
