name: CheckMerge

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_availability:
    runs-on: windows-latest
    steps:
      - name: Check Label
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "needmerge"
          pull-request-number: "${{ github.event.pull_request.number }}"
      - uses: actions/checkout@v1
      - name: Check Weblate
        run: |
          git remote add weblate http://Nullpinter:${{ BAKA_GOURD_WL_API_KEY }}@weblate-t.exz.me/git/langpack/_no_edit_base_component/
          git remote update weblate
          git merge weblate/main
