name: Label PRs

on:
- pull_request

permissions:
  actions: read/write
  checks: read/write
  contents: read/write
  deployments: read/write
  issues: none
  pull-requests: read/write
  repository-projects: read/write
  statuses: read/write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
