name: Spider

on:
  schedule:
  - cron: "0/30 * * * *"

env:
  token: ${{ secrets.token }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: run
      run: dotnet run --configuration Release --project ./src/Spider/Spider.csproj
      
